-- Create the database and schema for the trade data pipeline.
CREATE DATABASE IF NOT EXISTS TRADE_DATA_PIPELINE;
USE DATABASE TRADE_DATA_PIPELINE;

CREATE SCHEMA IF NOT EXISTS TRADE_DATA_PIPELINE.PUBLIC;
USE SCHEMA TRADE_DATA_PIPELINE.PUBLIC;
