-- Create a rejected trades table for invalid or failed trade records.
USE DATABASE TRADE_DATA_PIPELINE;
USE SCHEMA TRADE_DATA_PIPELINE.PUBLIC;

CREATE TABLE IF NOT EXISTS REJECTED_TRADES (
  TRADE_ID VARCHAR(50),
  TIMESTAMP TIMESTAMP_NTZ,
  SYMBOL VARCHAR(20),
  SIDE VARCHAR(10),
  QUANTITY NUMBER(38,0),
  PRICE NUMBER(18,4),
  CURRENCY VARCHAR(10),
  VENUE VARCHAR(50),
  VERSION NUMBER(38,0),
  MATURITY_DATE DATE,
  REJECTION_REASON VARCHAR(1000),
  SOURCE_FILE VARCHAR(255),
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
