-- Create a raw trades table to store ingested trade data.
USE DATABASE TRADE_DATA_PIPELINE;
USE SCHEMA TRADE_DATA_PIPELINE.PUBLIC;

CREATE TABLE IF NOT EXISTS RAW_TRADES (
  TRADE_ID VARCHAR(50) NOT NULL,
  TIMESTAMP TIMESTAMP_NTZ NOT NULL,
  SYMBOL VARCHAR(20) NOT NULL,
  SIDE VARCHAR(10) NOT NULL,
  QUANTITY NUMBER(38,0) NOT NULL,
  PRICE NUMBER(18,4) NOT NULL,
  CURRENCY VARCHAR(10) NOT NULL,
  VENUE VARCHAR(50) NOT NULL,
  VERSION NUMBER(38,0) NOT NULL,
  MATURITY_DATE DATE NOT NULL,
  STATUS VARCHAR(20),
  REJECTION_REASON VARCHAR(1000),
  SOURCE_FILE VARCHAR(255),
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
